### ISSUE TITLE
Float cell size

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1000]
The cell size is stored as float and this is causing rounding error. 

Testing procedure

- [X] Integer on the Control Table while creating the geopackage 
- [ ] Integer on the Control Table after creating the grid
- [ ] Integer on the FLO-2D Grid Info toolbar (Cell Size)

**Comment by FLO-2DKaren** [comment]
And review the code for the following to see where cell_size might be factoring in to other calculations such as 
Elevation Warp
Rainfall Warp
Infiltration averages
N value averages
arf/wrf calculations

keyword search for
cellsize
cell_size

Algorithms we might want to review include:
poly2poly
poly2grid
poly2polygeos

**Comment by rpachaly** [comment]
The Computational Domain layer (user_model_boundary) has the cell_size field as REAL. I converted the cell_size on the code to integer, but I think that the better would be to modify the geopackage to INT. However, I don't if it is worth it considering such a small modification.

**Comment by rpachaly** [comment]
The cell size is used in many portions of the code. It is retrieved from the Control Table (an integer now) by the function self.gutils.get_cont_par("CELLSIZE"). Then, it is converted to float to be used in many types of calculations. I think this is OK.

I just want to run some more tests before I push the branch.

**Comment by FLO-2DKaren** [comment]
OK if you want, we can do a comparison between some of the values like infi tables n value tables and such.

**Comment by FLO-2DKaren** [comment]
I just realized something dumb.  

When I applied the int to the cell size field, it just drops the decimals so it will provide 29 or 30 for the grid cell size.  This makes sense but I didn't think about it when I tried it in the plugin.

I know this point is not important because you are now using the cell size variable in the cont table.   It's just something to note for future calculators.  

I'm not worried that any current code is doing this.

**Comment by rpachaly** [comment]
> OK if you want, we can do a comparison between some of the values like infi tables n value tables and such.

I'm doing this. I just found some bugs on the RealTime Rainfall and I'm fixing it.

**Comment by FLO-2DKaren** [comment]
I have identified these line items.  I added them to this list because they have division or multiplication or they do math on a variable that might need to be rounded before it is converted.

**Can you check if any of these need a math.ceiling or round()?**


**grid_tools.py**
	Line  740:         col = int((xx - xmin) / cell_size) + 2
	Line  741:         row = int((yy - ymin) / cell_size) + 2

	Line 1732:                 farf = int(1 if f["calc_arf"] == NULL else f["calc_arf"])
	Line 1733:                 fwrf = int(1 if f["calc_wrf"] == NULL else f["calc_wrf"])

	Line 2106:             cell = int(cell)

	Line 2276:     #             cell = int(cell)

	Line 2841:     col = int((float(x) - self.xMinimum) / self.cell_size) + 2
	Line 2842:     row = int((float(y) - self.yMinimum) / self.cell_size) + 2

**schematic tools.py**

	Line  476:         maskdir1 = np.zeros(flatID.shape, dtype=int) + int(nullVal)
	Line  487:         maskdir2 = np.zeros(flatID.shape, dtype=int) + int(nullVal)

	Line  741:                 n1 = int(c_p1_a / (pi / 4)) % 8
	Line  742:                 n2 = int(c_p2_a / (pi / 4)) % 8

	Line 1802:             if int(azimuth) % 90 == 0:

**bc_editor_widget.py**
Robson,  I only added these two because the **State** is listed here and I know you are looking into this tool related to it's activation states.  I don't think these two are problematic with respect to setting the int().

	Line  151:                 interval = int(interval)
	Line  156:         state = str(int(self.interval_ckbx.isChecked()))

**dlg_sampling_point_elev.py**

	Line 109:         cachemax_min = int(point_elev.gdal_default_cachemax / (1024 * 1024.0))  # MB

**storm_drain_editor_widget.py**

	Line  111:             mins = int(mins * 60)

	Line 2969:                     + str(int(len(pattern_rows) / 24))
	Line 3323:             layer.triggerRepaint()
	Line 3860:                         currentHour = int(currentHour)
	Line 3861:                         minutes = int(minutes) / 60
	Line 3862:                         seconds = int(seconds) / 3600

**point_elev.py**
	Line 273:     col = int((x - ulX) / xDist)
	Line 274:     row = int((ulY - y) / xDist)
	Line 511:     rows = int((ymax - ymin) / cell_size)
	Line 512:     cols = int((xmax - xmin) / cell_size)

**Comment by FLO-2DKaren** [comment]
Comparison Test
Here is the project
https://flo-2d.sharefile.com/d-sfd51944a132e40e9804ea13fe6a6284a

IMPORTANT Put the project here and it will should be able to find all of the layers it needs.
C:\Users\Public\Documents\FLO-2D PRO Documentation\Example Projects\QGIS Tutorials\QGIS Lesson 1

Calculation Tests
1. Elevation regular method. 
2. Infiltration New Method.  My link has the FCDMC layers loaded.
3. Nvalue Area Average method.

My .DAT files are loaded on the link too.  You can compare your .dat files to mine.

**Comment by FLO-2DKaren** [comment]
Robson,  I almost forgot....
The variable grid_area is also being applied in poly2grid and possibly other places.  It is also being calculated from the geometry instead of entered as a float number.

**Comment by rpachaly** [comment]
**grid_tools.py**
740 & 741: No need, it sets the cell size based on the Control Table. 
1732 & 1733: Yes, here it is good to round it before applying the int function. 
2106: Don’t think this function is being used on the code anymore. But all the cells are integers, so I don’t think is a problem
2841 & 2842: Don’t think this is going to impact a lot, but I’ll round it before applying the int function for the sake of precaution. 

**schematic tools.py**
476 & 487: This one I don’t quite understand, let’s keep the way it is. 
741 & 742: Yes, it should be rounded. 
1802: Yes, it should be rounded.

**bc_editor_widget.py**
151: No need, this is a switch and always an integer. 
156: No need, this is a switch and always an integer.

**dlg_sampling_point_elev.py**
109: Yes, it should be rounded.
118: Yes, it should be rounded.

**storm_drain_editor_widget.py**
111: Yes, it should be rounded.  
2969: No need, this is a counter and it is in a print statement.
3860 & 3861 & 3862: Yes, it should be rounded.  

**point_elev.py**
273 & 274: It is not going to impact a lot but it should be rounded.
511 & 512: It is not going to impact a lot but it should be rounded. 

I'll start the testing now.

**Comment by rpachaly** [comment]
> Robson, I almost forgot.... The variable grid_area is also being applied in poly2grid and possibly other places. It is also being calculated from the geometry instead of entered as a float number.

What do you think about calculating it as cell_size^2?

**Comment by rpachaly** [comment]
TOPO.DAT match
RAIN.DAT match
MANNINGS_N.DAT match
INFLOW.DAT match

INFIL.DAT does not match. And it does not match even with my master branch. I'm wondering what could be this difference?

**Comment by rpachaly** [comment]
And it is happing only on the hydraulic conductivity column

**Comment by FLO-2DKaren** [comment]
This is what I used
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/3d4fc4fe-babc-4e72-9b9b-f9b3652b1c88)

**Comment by rpachaly** [comment]
I figure out in this exact moment!!! I was checking the Vegetation cover. There are very small differences in the INFIL.DAT, in the third decimal place. I believe that it is all good to push the branch. My INFIL.DAT:

[INFIL.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/12834896/INFIL.zip)

**Comment by FLO-2DKaren** [comment]
Don't forget the metadata.txt

**Comment by rpachaly** [comment]
It did no pass the tests, I'm checking it right now.

**Comment by FLO-2DKaren** [comment]
ERROR: test_poly2grid (test.test_grid_tools.TestGridTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qgis-flo-2d-plugin/qgis-flo-2d-plugin/test/test_grid_tools.py", line 50, in test_poly2grid
    for n, gid in poly2grid(glayer, rlayer, None, True, False, False, 1, "manning"):
  File "/home/runner/work/qgis-flo-2d-plugin/qgis-flo-2d-plugin/flo2d/flo2d_tools/grid_tools.py", line 757, in poly2grid
    grid_area = float(gutils.get_cont_par("CELLSIZE")) ** 2
AttributeError: 'QgsVectorLayer' object has no attribute 'get_cont_par'

**Comment by rpachaly** [comment]
It is on the test the issue. I changed the poly2grid function. It must receive the gutils as first argument.

poly2grid(gutils, glayer, rlayer, None, True, False, False, 1, "manning"):

* Gutils is used to get the CELLSIZE on the Control Table

**Comment by rpachaly** [comment]
It is my first having trouble with the tests. How do we proceed?

**Comment by FLO-2DKaren** [comment]
I wonder why it's trying to connect to a vector layer?  Maybe it used to connect to grid layer but now it connects to a table not a vector layer.

**Comment by rpachaly** [comment]
The issue is the following: 

The test test_poly2grid is trying to run poly2grid using the following code

`poly2grid(glayer, rlayer, None, True, False, False, 1, "manning")`

On my branch, I changed the poly2grid function by adding a new argument (gutils) before the glayer. So, the poly2grid must be called in the code like this: 

`poly2grid(GUTILS, glayer, rlayer, None, True, False, False, 1, "manning")`

I updated the whole code where poly2grid is called to add this new argument. 

I believe that the issue now is on the test itself, we need to modify the test script to call the poly2grid function correctly.

**Comment by FLO-2DKaren** [comment]
The test script is fairly easy to modify.  Let me know if you can't access it or something.

**Comment by FLO-2DKaren** [comment]
I'm trying this right now.

    def test_poly2grid(self):
        grid = os.path.join(VECTOR_PATH, "grid.geojson")
        roughness = os.path.join(VECTOR_PATH, "roughness.geojson")
        glayer = QgsVectorLayer(grid, "grid", "ogr")
        rlayer = QgsVectorLayer(roughness, "roughness", "ogr")
        n_values = []
        for n, gid in poly2grid(gutils, glayer, rlayer, None, True, False, False, 1, "manning"):
            n_values.append(float(n))
        man_sum = sum(n_values)
        self.assertEqual(round(man_sum, 1), 16.5)
        expected = {0.5, 0.3, 0.1}
        self.assertSetEqual(set(n_values), expected)

It's still failing so I think we need to import something else.  It's defined in the Zonal Statistics Class.

I think it's easy to fix for you through so I'll go work on something else.

**Comment by rpachaly** [comment]
Yes, the gutils must be imported before it could be called. I'll fix it and push the branch again.

**Comment by FLO-2DKaren** [comment]
Hi Robson,

I think some tests are being skipped and we might need to add some for new data files.  I'll merge the code now.
