### ISSUE TITLE
Error Message - Debug Branch

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1136]
When loading a project from QGIS 3.28, I see this error message:
This is the Debug Branch.

An error has occurred while executing Python code: 

TypeError: argument of type 'NoneType' is not iterable 
Traceback (most recent call last):
  File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 1378, in load_gpkg_from_proj
    if '%20' in new_gpkg:
TypeError: argument of type 'NoneType' is not iterable

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.34.1-Prizren Prizren, 133927424d

**Comment by FLO-2DKaren** [comment]
I was trying to load the coastal project.  I'm going to try it in QGIS 3.28 instead of 3.34.

**Comment by FLO-2DKaren** [comment]
I can confirm that this message is happening on Both versions of QGIS.

An error has occurred while executing Python code: 

TypeError: argument of type 'NoneType' is not iterable 
Traceback (most recent call last):
  File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 1378, in load_gpkg_from_proj
    if '%20' in new_gpkg:
TypeError: argument of type 'NoneType' is not iterable


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.12-Firenze Firenze, dcc633b2de

**Comment by FLO-2DKaren** [comment]
Sorry this message is wrong.  I should have used Open FLO-2D Project Instead of loading from the qgz.
