### ISSUE TITLE
Python Error Zamora Channel

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1223]
2024-03-19T17:14:53     WARNING    Traceback (most recent call last):
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\xs_editor_widget.py", line 1164, in interpolate_channel_elevation
              xs_survey = self.save_chan_dot_dat_with_zero_natural_cross_sections()
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\xs_editor_widget.py", line 1554, in save_chan_dot_dat_with_zero_natural_cross_sections
              natural_channel_section_number_dict[usr_xs_fid],
             KeyError: 2

Don't delete User Cross Sections table when clear schema data.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/89bc5cb4-9f69-499d-8270-c3eb2438628a

**Comment by rpachaly** [comment]
Done on 8373d629c21dca0d79842244c52282f9d322a67a
