### ISSUE TITLE
Save Cross Section Error Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1265]
Hi Robson,

I just downloaded the plugin this morning so I'm testing one merged on 4/1/2024 or thereabout.

I found an error with the cross section save process.  I hope it is an easy fix.  The data seems ok but the error message appears and the data is not interpolating.

https://flo-2d.sharefile.com/d-s2c53c26e07fb4c31beaa22bb3a098050

**Comment by rpachaly** [comment]
Ok, working on this.

**Comment by FLO-2DKaren** [comment]
I hope it's the same issue JJ found.

**Comment by FLO-2DKaren** [comment]
Here is the error message I copied during the video.  I don't think it is necessary but just to document it.

2024-04-02T08:56:18     INFO    There was an error querying the database C:/Users/Public/Documents/FLO-2D PRO Documentation/Example Projects/Coastal 2D Training/Coastal Project_v1.0.0.gpkg: no such table: qgis_projects
2024-04-02T08:59:42     WARNING    Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()

2024-04-02T08:59:42     WARNING    Traceback (most recent call last):
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\xs_editor_widget.py", line 170, in 
              self.user_xs_lyr.editingStopped.connect(lambda: self.populate_xsec_cbo(show_last_edited=True))
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\xs_editor_widget.py", line 327, in populate_xsec_cbo
              self.current_xsec_changed(self.xs_cbo.currentData())
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\xs_editor_widget.py", line 398, in current_xsec_changed
              row = self.xs.get_row()
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2dobjects.py", line 193, in get_row
              values = [x if x is not None else "" for x in self.execute(qry, (self.fid,)).fetchone()]
             TypeError: 'NoneType' object is not iterable

**Comment by rpachaly** [comment]
It is the same error that @FLO-2DJJ got.

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/4abdf159-ac33-45cf-8966-1f77e5193b20

On branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/save-xc-error

**Comment by FLO-2DKaren** [comment]
Awesome.  I'll test it right now.

**Comment by FLO-2DKaren** [comment]
Well this is going to be annoying for you but I am getting a can't schematize error message because of bank data.  I think my banks are ok so maybe this is just a bad error message that stops the schematize.

I attached the broken project here. 

https://flo-2d.sharefile.com/d-s19e02ab193c248879e8c0447f64aafe6

**Comment by rpachaly** [comment]
Don't worry Karen, we'll have all sorted out.

**Comment by rpachaly** [comment]
I cannot reproduce the same error. Which version of QGIS are you using?

**Comment by FLO-2DKaren** [comment]
Well let me restart it and try again.  I'll get a video this time.

**Comment by FLO-2DKaren** [comment]
Oh good!!!  I just needed to restart the project.  I'm going to close this issue and move on to the other tests.
