### ISSUE TITLE
FLO-2D Info Tool can't find Layer List

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1363]
I got this error when I tried to use the info tool.  I set the setting to the correct Run path but the tool still wont work.
QGIS 3.36.3
Master Plugin as of 5-29-2024

2024-05-29T21:00:16     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 149, in activate
              self.update_lyrs_list()
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 37, in update_lyrs_list
              self.lyrs_list = self.lyrs.list_group_vlayers(self.lyrs.group, skip_views=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\layers.py", line 2075, in list_group_vlayers
              if lyr.layer().type() == 0 and lyr.layer().geometryType()               ^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'type'
             
2024-05-29T21:00:19     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 64, in canvasReleaseEvent
              res = self.identify(e.x(), e.y(), self.lyrs_list, QgsMapToolIdentify.TopDownAll)
              ^^^^^^^^^^^^^^
             AttributeError: 'InfoTool' object has no attribute 'lyrs_list'
             
2024-05-29T21:01:23     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 155, in deactivate
              self.lyrs.root.visibilityChanged.disconnect(self.update_lyrs_list)
             TypeError: 'method' object is not connected
             
2024-05-29T21:01:34     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 149, in activate
              self.update_lyrs_list()
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 37, in update_lyrs_list
              self.lyrs_list = self.lyrs.list_group_vlayers(self.lyrs.group, skip_views=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\layers.py", line 2075, in list_group_vlayers
              if lyr.layer().type() == 0 and lyr.layer().geometryType()               ^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'type'
             
2024-05-29T21:01:38     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\info_tool.py", line 64, in canvasReleaseEvent
              res = self.identify(e.x(), e.y(), self.lyrs_list, QgsMapToolIdentify.TopDownAll)
              ^^^^^^^^^^^^^^
             AttributeError: 'InfoTool' object has no attribute 'lyrs_list'

**Comment by FLO-2DKaren** [comment]
I'm hoping this is an error related to me breaking my test not something wrong with the plugin.  I've done lots of saving and weird things with this GeoPackage.

**Comment by rpachaly** [comment]
Hi Karen, 

I was trying to break it here and nothing happened. I tried this in multiple projects:

Running the tool with and without the correct path on the Run path
Selecting external layers that are in top of the user layers

Can you send me the geopackage with the bug so I can explore it further?

**Comment by FLO-2DKaren** [comment]
Let's just ignore it.  I don't trust that geopackage.  It's one of the testers and it's probably pretty messed up from importing stuff.
