### ISSUE TITLE
Quick Run Test

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1420]
New Issue when using Quick Run  

2024-07-24T19:50:27     WARNING    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\Student/python/plugins\flo2d\flo2d.py", line 424, in 
              lambda: self.quick_run_flopro(),
              ^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\Student/python/plugins\flo2d\geopackage_utils.py", line 35, in wrapper
              return fn(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\Student/python/plugins\flo2d\flo2d.py", line 1275, in quick_run_flopro
              export_calls.remove("export_tailings")
             ValueError: list.remove(x): x not in list

**Comment by FLO-2DKaren** [comment]
This test was on a project with just grid and rainfall but it had 2 million cell count.

**Comment by rpachaly** [comment]
Can you share this project Karen?

**Comment by rpachaly** [comment]
Based on your traceback I figured out the error. The quick run function was wrongly removing the 'export_tailings' under the Inflow Elements, it should be performed under the Tailings. This fix must solve the quick run issue. 

Done and merged on: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1425

**Comment by FLO-2DKaren** [comment]
Quick Run test complete.
