### ISSUE TITLE
Remove a layer but no FLO-2D GeoPackage connected

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1459]
I'm getting a python error when I remove a layer but I don't have a FLO-2D GeoPackage connected.

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1454#issuecomment-2270192070_

**Comment by rpachaly** [comment]
There is also a bug when loading a project that is not FLO-2D

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1466

**Comment by FLO-2DKaren** [comment]
![load and unload a file](https://github.com/user-attachments/assets/46c13d8a-7fb0-47db-a584-5027f8114e27)

2024-08-06T21:27:00     WARNING    Traceback (most recent call last):
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 4672, in change_external_layer_type
              external_layers = self.gutils.execute(
              ^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'execute'
             
2024-08-06T21:28:39     WARNING    Traceback (most recent call last):
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 4672, in change_external_layer_type
              external_layers = self.gutils.execute(
              ^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'execute'

**Comment by rpachaly** [comment]
I don't see this error on the current master. Did you test it before https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1466 was merged?

**Comment by FLO-2DKaren** [comment]
Wrong branch.  This is working fine.
